services:
  neo4j:
    image: neo4j:5.15-community
    environment:
      NEO4J_AUTH: neo4j/graphmcp2024
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:7474/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  graph-mcp:
    build:
      context: ..
      dockerfile: graph_mcp/Dockerfile
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: graphmcp2024
    depends_on:
      neo4j:
        condition: service_healthy
    # Run the MCP server directly
    command: uv run python -m graph_mcp.mcp_server
    stdin_open: true
    tty: false

volumes:
  neo4j_data:
  neo4j_logs: