services:
  devcontainer:
    hostname: ${PROJECT_NAME:-app}-devcontainer
    container_name: ${PROJECT_NAME:-app}-devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.claude:/home/devuser/.claude:cached
      - type: bind
        source: /Users/bruk.habtu/claude.json
        target: /home/devuser/claude.json
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
    depends_on:
      - neo4j
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`devcontainer.${PROJECT_NAME}.localhost`)"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
    networks:
      - neoalchemy
  neo4j:
    hostname: ${PROJECT_NAME:-app}-neo4j
    container_name: ${PROJECT_NAME:-app}-neo4j
    image: neo4j:4.4
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-password}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    labels:
      - "traefik.enable=true"
      # HTTP Browser interface
      - "traefik.http.routers.neo4j.rule=Host(`neo4j.${PROJECT_NAME}.localhost`)"
      - "traefik.http.services.neo4j.loadbalancer.server.port=7474"
      # Bolt protocol
      - "traefik.tcp.routers.neo4j-bolt.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.neo4j-bolt.entrypoints=bolt"
      - "traefik.tcp.routers.neo4j-bolt.service=neo4j-bolt"
      - "traefik.tcp.services.neo4j-bolt.loadbalancer.server.port=7687"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - neoalchemy
  traefik:
    hostname: ${PROJECT_NAME:-app}-traefik
    container_name: ${PROJECT_NAME:-app}-traefik
    image: traefik:v2.9
    ports:
      - "80:80"    # Web interface
      - "7687:7687"  # For Neo4j bolt protocol
    command:
      - "--api.insecure=true"  # Enable the dashboard
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.bolt.address=:7687"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${PROJECT_NAME}.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
    networks:
      - neoalchemy
volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  neoalchemy:
    driver: bridge